services:
  jest:
    build:
      context: .
      target: jest
    environment:
    - AWS_ACCESS_KEY_ID=minioadmin
    - AWS_SECRET_ACCESS_KEY=minioadmin
    - PGUSER=cjworkbench
    - PGPASSWORD=cjworkbench
    - PGDATABASE=cjworkbench
    - PGHOST=database
    - PGPORT=5432
    depends_on: [ database, gcs-server, s3-server ]
    volumes:
    - ./src:/app/src:ro
    - ./test:/app/test:ro
    command: [ "npm", "test" ]

  database:
    image: postgres:13.3
    environment:
    - POSTGRES_USER=cjworkbench
    - POSTGRES_PASSWORD=cjworkbench
    - POSTGRES_DB=cjworkbench
    volumes:
    - ./test/sql:/docker-entrypoint-initdb.d:ro

  gcs-server:
    image: fsouza/fake-gcs-server:v1.29.1
    volumes:
    - ./test/data:/data:ro
    command: [ "-port", "80", "-scheme", "http" ]

  s3-server:
    image: minio/minio:RELEASE.2021-07-08T01-15-01Z
    environment:
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
    - ./test/data:/data:rw  # rw because minio needs to write .minio.sys/
    command: [ "server", "/data", "--address", ":80" ]
