INSERT INTO workflow (id, public, secret_id)
VALUES
(6, FALSE, 'secret-id'),
(7, FALSE, 'good-secret'),
(8, TRUE, ''),
(9, TRUE, ''),
(10, TRUE, ''),
(11, FALSE, 'secret-id'),
(12, FALSE, 'right-secret'),
(13, FALSE, 'right-secret'),
(14, FALSE, 'right-secret'),
(16, TRUE, ''),
(17, TRUE, ''),
(18, TRUE, ''),
(19, TRUE, ''),
(20, FALSE, 'missing-secret'),
(21, TRUE, ''),
(22, TRUE, ''),
(23, TRUE, ''),
(24, TRUE, ''),
(25, FALSE, 'missing-secret'),
(26, FALSE, ''),
(27, FALSE, ''),
(28, FALSE, ''),
(29, FALSE, ''),
(30, FALSE, ''),
(34, TRUE, 'secret-not-used');
